In [1]:
import numpy as np 
import pandas as pd 
import matplotlib.pyplot as plt

In [2]:
df = pd.read_csv("https://raw.githubusercontent.com/benvictoria17/DataAnalytics/main/dataset/college%20admission/College_admission.csv")
df = df.rename(columns={'rank':'Rank'})
df.head()

admit  gre   gpa  ses  Gender_Male  Race  Rank
0      0  380  3.61    1            0     3     3
1      1  660  3.67    2            0     2     3
2      1  800  4.00    2            0     2     1
3      1  640  3.19    1            1     2     4
4      0  520  2.93    3            1     2     4

In [3]:
dummies1 = pd.get_dummies(df.ses, prefix='ses')
dummies2 = pd.get_dummies(df.Race, prefix='Race')
dummies3 = pd.get_dummies(df.Rank, prefix='Rank')
new_df = pd.concat([df,dummies1,dummies2,dummies3] , axis='columns')
df = new_df.drop(['ses','Race' , 'Rank'], axis='columns')
df.head()

admit  gre   gpa  Gender_Male  ses_1  ses_2  ses_3  Race_1  Race_2  Race_3  \
0      0  380  3.61            0      1      0      0       0       0       1   
1      1  660  3.67            0      0      1      0       0       1       0   
2      1  800  4.00            0      0      1      0       0       1       0   
3      1  640  3.19            1      1      0      0       0       1       0   
4      0  520  2.93            1      0      0      1       0       1       0   

   Rank_1  Rank_2  Rank_3  Rank_4  
0       0       0       1       0  
1       0       0       1       0  
2       1       0       0       0  
3       0       0       0       1  
4       0       0       0       1

In [4]:
x = df.iloc[:,1:]
y = df.iloc[:,0]
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.25, random_state = 1,stratify = y)
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import confusion_matrix, accuracy_score
classifier = LogisticRegression(random_state = 0)
classifier.fit(x_train, y_train)
y_pred = classifier.predict(x_test)
cm = confusion_matrix(y_test, y_pred)
print(cm)
acc_log = accuracy_score(y_test, y_pred)

[[63  5]
 [25  7]]


/usr/local/lib/python3.9/site-packages/sklearn/linear_model/_logistic.py:763: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


In [5]:
from sklearn.svm import SVC
classifier = SVC(kernel = 'linear', random_state = 0)
classifier.fit(x_train, y_train)
y_pred = classifier.predict(x_test)
cm = confusion_matrix(y_test, y_pred)
print(cm)
acc_svm = accuracy_score(y_test, y_pred)

[[63  5]
 [27  5]]


In [6]:
from sklearn.tree import DecisionTreeClassifier
classifier = DecisionTreeClassifier(criterion = 'entropy', random_state = 0)
classifier.fit(x_train, y_train)
y_pred = classifier.predict(x_test)
cm = confusion_matrix(y_test, y_pred)
print(cm)
acc_dtree = accuracy_score(y_test, y_pred)

[[45 23]
 [17 15]]


In [7]:
from sklearn.ensemble import RandomForestClassifier
classifier = RandomForestClassifier(n_estimators = 10, criterion = 'entropy', random_state = 0)
classifier.fit(x_train, y_train)
y_pred = classifier.predict(x_test)
cm = confusion_matrix(y_test, y_pred)
print(cm)
acc_rforest = accuracy_score(y_test, y_pred)

[[57 11]
 [25  7]]


In [8]:
models = pd.DataFrame({
    'Model': ['Logistic Regression','Support Vector Machines',  
              'Decision Tree','Random Forest'],
    'Score': [acc_log, acc_svm, 
              acc_dtree,acc_rforest]})
models.sort_values(by='Score', ascending=True)

Model  Score
2            Decision Tree   0.60
3            Random Forest   0.64
1  Support Vector Machines   0.68
0      Logistic Regression   0.70

In [10]:
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import confusion_matrix, accuracy_score
classifier = LogisticRegression(random_state = 0)
classifier.fit(x_train, y_train)
y_pred = classifier.predict(x_test)
cm = confusion_matrix(y_test, y_pred)
print(cm)
acc_log = accuracy_score(y_test, y_pred)

[[63  5]
 [25  7]]


/usr/local/lib/python3.9/site-packages/sklearn/linear_model/_logistic.py:763: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


In [11]:
from sklearn.svm import SVC
classifier = SVC(kernel = 'linear', random_state = 0)
classifier.fit(x_train, y_train)
y_pred = classifier.predict(x_test)
cm = confusion_matrix(y_test, y_pred)
print(cm)
acc_svm = accuracy_score(y_test, y_pred)

[[63  5]
 [27  5]]


In [12]:
from sklearn.tree import DecisionTreeClassifier
classifier = DecisionTreeClassifier(criterion = 'entropy', random_state = 0)
classifier.fit(x_train, y_train)
y_pred = classifier.predict(x_test)
cm = confusion_matrix(y_test, y_pred)
print(cm)
acc_dtree = accuracy_score(y_test, y_pred)

[[45 23]
 [17 15]]


In [13]:
from sklearn.ensemble import RandomForestClassifier
classifier = RandomForestClassifier(n_estimators = 10, criterion = 'entropy', random_state = 0)
classifier.fit(x_train, y_train)
y_pred = classifier.predict(x_test)
cm = confusion_matrix(y_test, y_pred)
print(cm)
acc_rforest = accuracy_score(y_test, y_pred)

[[57 11]
 [25  7]]


In [14]:
models = pd.DataFrame({
    'Model': ['Logistic Regression','Support Vector Machines',  
              'Decision Tree','Random Forest'],
    'Score': [acc_log, acc_svm, 
              acc_dtree,acc_rforest]})
models.sort_values(by='Score', ascending=True)

Model  Score
2            Decision Tree   0.60
3            Random Forest   0.64
1  Support Vector Machines   0.68
0      Logistic Regression   0.70

In [15]:
submission = pd.DataFrame(y_pred)
submission.to_csv('Submission.csv')